import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import RibbonMenu from '@/components/ui/RibbonMenu';
import Header from '@/components/ui/Header';
import WelcomeSection from '@/components/ui/WelcomeSection';
import Popups from '@/components/ui/Popups';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <div className="min-h-screen bg-gray-50">
          <Header />
          <RibbonMenu />
          <WelcomeSection />
          {children}
          <Popups />
        </div>
      </body>
    </html>
  );
}
